=head1 Game Lobby

All methods in this section can be carried out by a connection to the B<game/lobby>
route.

=head2 Sessions

A session ID is used to identify the client to the server. A session ID
is initially provided by the server and this should be retained by the client and used in
every subsequent Web Socket call to the server. Once you have a session you should
continue to use it for all future sessions.

A session may 'time-out' (after a few hours) but by keeping the same session ID
the server will still be able to retain 'state' for you to improve your browsing
experience.

Any calls described below which require a B<session> will be mandatory. If you don't
supply a B<session> then the call will be rejected.




=head2 Server : lobby

A B<lobby> status will be sent by the Game Lobby shortly after the user has
made a connection or in the case where the lobby status changes.

    {
        "code"      : 0,
        "data"      : "lobby",
        "message"   : "Welcome to the Game Lobby",
    }

=head3 code

The numeric code representing the B<lobby_status> where B<0> represents success
and any other value indicates a fault.

=head3 message

A message from the server, for example the time at which the server is expected
to be available again if the server is off-line for maintenance.




=head2 Client : get_session

Get a new session ID. Note, you should only do this if you don't already have a
session ID, even one that has expired. You may need to log in if you have an
expired session but it will enable the server to keep some 'state' information
for you between sessions.

    {
        "id"        : "123",
    }

=head3 id (optional)

An ID to identify this message so you can tie up the server response to this request.

=head3 RESPONSE

The server responds with a B<Server : get_session> message.




=head2 Server : get_session

Server response to a B<Client : get_session> request.

    {
        "code"      : 0,
        "message"   : "new session",
        "session"   : "1234-ABCD-5678-EF01-000000",
        "id"        : "123"
    }

B<code> B<message> and B<id> as defined in server status.

=head3 session

A unique code for the client to use in all subsequent calls. Refer to the Session
information above.

=head3 RESPONSE

No response is required by the client.




=head2 Client : get_radius

Get the API Key for the LoginRadius social login.

    {
        "id"        : "123",
    }

=head3 id (optional)

An ID to identify this message so you can tie up the server response to this request.

=head3 RESPONSE

The server responds with a B<Server : get_radius> message.




=head2 Server : get_radius

Server response to a B<Client : get_radius> request.

    {
        "code"              : 0,
        "message"           : "new session",
        "radius_api_key"    : "78855680-671c-4c70-b194-2e392a0a7c81",
        "id"                : "123"
    }

B<code> B<message> and B<id> as defined in server status.

=head3 radius_api_key

The site specific API Key to use with Radius Social Login.

=head3 RESPONSE

No response is required by the client.




=head2 Client : login_with_email_code

Attempt to log in with an B<email_code> (as a result of either registering or
requesting a forgotten password email).

    {
        "email_code"   : "1234-ABCD-5678-EF01-000000",
    }

=head3 email_code (required)

The code provided in your email.

=head3 RESPONSE

The server will respond with a B<Server : login_with_email_code> message.




=head2 Server : login_with_email_code

This is a response to B<Client : login_with_email_code>,

    {
        "username"  : "james_bond",
    }

=head3 username

The name of the account you have logged into.

=head3 RESPONSE

No response is necessary.




=head2 Client : login_with_password

Attempt to log in with a B<username> B<password> combination. If you have a session
variable from a previous session then please re-use it. This will allow the server
to recover state from that session.

    {
        "session"   : "1234-ABCD-5678-EF01-000000",
        "username"  : "james_bond",
        "password"  : "Tops3cr3t"
    }

=head3 session (required)

Your session variable.

=head3 username (required)

Your account user name

=head3 password (required)

Your account password

=head3 RESPONSE

The server will respond with a B<Server : login_with_password> message.




=head2 Server : login_with_password

This is a response to B<Client : login_with_password>,

    {
        "username"  : "james_bond",
    }

=head3 username

The name of the account you have logged into.

=head3 RESPONSE

No response is necessary.




=head2 Client : logout

Send a logout message.

    {
        "session"   : "1234-ABCD-5678-EF01-000000",
    }

=head3 session (required)

Your session variable.

=head3 RESPONSE

The server responds with a B<Server : logout> message.




=head2 Server : logout

This is a response to B<Client : logout>,

It sends a standard status message.




=head2 Client : register

Send a registration message from the Client to the server.

    {
        "session"   : "1234-ABCD-5678-EF01-000000",
        "username"  : "james_bond",
        "password"  : "tops3cret",
        "email"     : "agent007@mi6.gov.co.uk",
        "id"        : "james_bond",
    }

On registering you will be sent an email which allows you to confirm your email
address. In the email will be a link which you need to follow. On clicking the
link it will verify your email address and unlock your account.

=head3 session (required)

Your session variable.

=head3 username (required)

The name you will use to log into the site. This must be at least 3 charaters long
and may consist of letters, numbers or punctuation.

=head3 password (required)

The password to authenticate you to the server. At least one upper-case character,
one lower-case character and either a numeric or punctuation character. The password
must also be at least 5 characters long.

=head3 email (required)

Your email address. You will not be able to log onto the server until your email
address has been verified. We will send a message with instructions on how to log
in to this email address, so make sure it is correct.

=head3 id (optional)

An ID to identify this message so you can tie up the server response to this request.

=head3 RESPONSE

The server will send a B<Server : register> message with the success or failure
of this call.




=head2 Server : register

Returns B<code> B<id> and B<message> (see L<intro.pod>)

The B<data> returned is the username.




=head2 Client : rooms

A client request to obtain the rooms which are available to join.

    {
        "session"       : "1234-ABCD-5678-EF01-000000",
        "id"            : "123",
        "continuous"    : "1",
    }

=head3 session (required)

Your session variable.

=head3 id (optional)

Unique ID to identify the return message;

=head3 continuous (optional)

If specified, and if set to B<1> will cause the server to send continuous
updates whenever the rooms status changes.

To stop continuous messages from the server send a B<Client : rooms> message
with B<continuous> set to B<0> or omitted altogether.

=head3 RESPONSE

The server will respond with B<Server : rooms> message and will continue to do
so whenever a rooms status changes (if B<continuous> is set to B<1>).




=head2 Server : rooms

A B<Server : rooms> message will be sent after a B<Client : rooms> request or
on a continuous basis (whenever there is a change) if selected by the client.

    {
        "rooms" : [
            {
            "room"      : "//spacebotwar.com/ws/game/zone1",
            "users"     : 113,
            "status"    : "open",
            },
            ...
            {
    }

=head3 rooms

A list of all rooms which are present. For each room the following information
will be provided.

=head3 room

The web socket URL for the room.

=head3 users

The number of users currently in that room

=head3 status

The current status of that room B<open> if the room is available for the user to
enter. Any other value indicates that the room is not available (e.g. B<closed>,
B<full> etc.).

=head3 RESPONSE

The client does not need to give a response.


